### ISSUE TITLE
JVM crash

### ISSUE THREAD

**Issue by 0xbaadf00d** [payzen/payzen-webservices-v5-sdk-java#19]
Hi,

We got this issue on our production servers with the last version of `payzen-webservices-v5-sdk-java` :

```
#> java -version
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b13, mixed mode)
```

```
#> uname -a
Linux sandbox.localdomain 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
#> cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

```
Uncaught error from thread [application-akka.actor.default-dispatcher-731] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSyst\
em[application]
java.lang.StackOverflowError
        at javax.net.ssl.HttpsURLConnection.getDefaultHostnameVerifier(HttpsURLConnection.java:246)
        at eu.payzen.webservices.sdk.util.PayzenHostnameVerifier.verify(PayzenHostnameVerifier.java:34)
        at eu.payzen.webservices.sdk.util.PayzenHostnameVerifier.verify(PayzenHostnameVerifier.java:34)
        at eu.payzen.webservices.sdk.util.PayzenHostnameVerifier.verify(PayzenHostnameVerifier.java:34)
        at eu.payzen.webservices.sdk.util.PayzenHostnameVerifier.verify(PayzenHostnameVerifier.java:34)
        --- TRUNCAT LOG ---
       at eu.payzen.webservices.sdk.util.PayzenHostnameVerifier.verify(PayzenHostnameVerifier.java:34)
       at eu.payzen.webservices.sdk.util.PayzenHostnameVerifier.verify(PayzenHostnameVerifier.java:34)
       at eu.payzen.webservices.sdk.util.PayzenHostnameVerifier.verify(PayzenHostnameVerifier.java:34)
       at eu.payzen.webservices.sdk.util.PayzenHostnameVerifier.verify(PayzenHostnameVerifier.java:34)
       at eu.payzen.webservices.sdk.util.PayzenHostnameVerifier.verify(PayzenHostnameVerifier.java:34)
       at eu.payzen.webservices.sdk.util.PayzenHostnameVerifier.verify(PayzenHostnameVerifier.java:34)
       at eu.payzen.webservices.sdk.util.PayzenHostnameVerifier.verify(PayzenHostnameVerifier.java:34)
       at eu.payzen.webservices.sdk.util.PayzenHostnameVerifier.verify(PayzenHostnameVerifier.java:34)
       at eu.payzen.webservices.sdk.util.PayzenHostnameVerifier.verify(PayzenHostnameVerifier.java:34)
       at eu.payzen.webservices.sdk.util.PayzenHostnameVerifier.verify(PayzenHostnameVerifier.java:34)
```

**Comment by profesorfalken** [comment]
Hello, 

What is value of  endpointHost variable in your _payzen-config.properties_ file?

Have you tried to disable the verifier? : _disableHostnameVerifier=true_


Regards
